# 指定端口号
server:
  port: 9006
# 指定名称
spring:
  application:
    name: tensquare-spit
    # 指定数据源及数据库
  data:
    mongodb:
      host: 192.168.8.128
      database: spitdb
  redis:
    host: 192.168.8.128

